### ISSUE TITLE
Invalid PDF format on ios

### ISSUE THREAD

**Issue by Zhanerkeb** [rbcprolabs/packages.flutter#159]
I wanted to launch app on Iphone 12 PRO Max then had an issue about Invalid PDF format on render.

Smartphone (please complete the following information):
 - Device: Iphone 12 Pro Max
 - Version 14.4

**Comment by stevenspiel** [comment]
If you are storing your document in `/assets`, make sure you include it in your `pubspec.yaml`

```yml
flutter:
  uses-material-design: true
  assets:
    - assets/file.pdf
```
