### ISSUE TITLE
Native PDF View: The plugin `native_pdf_view` doesn't have a main class defined

### ISSUE THREAD

**Issue by michael-ottink** [rbcprolabs/packages.flutter#209]
**Describe the bug**
I get the following error when installing the package with 

flutter pub add native_pdf_view

The plugin `native_pdf_view` doesn't have a main class defined in C:\Users\USERNAME\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\native_pdf_view-1.0.3\android\src\main\java\io\scer\native_pdf_view\NativePDFViewPlugin.java or
C:\Users\USERNAME\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\native_pdf_view-1.0.3\android\src\main\kotlin\io\scer\native_pdf_view\NativePDFViewPlugin.kt. This is likely to due to an incorrect `androidPackage:
io.scer.native_pdf_view` or `mainClass` entry in the plugin's pubspec.yaml.
If you are the author of this plugin, fix the `androidPackage` entry or move the main class to any of locations used above. Otherwise, please contact the author of this plugin and consider using a different plugin in the        
meanwhile.

This is my pubspec.yml

```
name: my_project_name
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^7.1.0
  bloc: ^7.0.0
  equatable: ^2.0.3
  font_awesome_flutter: ^9.1.0
  flutter_treeview: ^1.0.4+1
  photo_view: ^0.12.0
  chewie: ^1.2.2
  video_player: ^2.1.12
  just_audio: ^0.9.5
  audio_session: ^0.1.5
  rxdart: ^0.27.1
  native_pdf_view: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/videos/
```

Device
 - Windows 10
 - 
**Additional context**
Flutter Version: 2.2.3
Dart Version: 2.13.4
