### ISSUE TITLE
not work on Windows

### ISSUE THREAD

**Issue by insinfo** [rbcprolabs/packages.flutter#258]
not work on windows
flutter: Error getting printing info: MissingPluginException(No implementation found for method  open.document.data on channel io.scer.native_pdf_renderer)

```dart 
Observer(builder: (_) {
                    if (controller.pdfContrachequeState ==
                        LoadingState.loading) {
                      return Center(
                        child: CircularProgressIndicator(),
                      );
                    }
                    if (controller.pdfContrachequeState == LoadingState.none) {
                      return Container();
                    }
                    if (controller.pdfContrachequeState == LoadingState.error) {
                      return Center(
                        child: Text('erro ao carregar o contracheque'),
                      );
                    }

                    final pdfController = PdfController(
                      document:
                          PdfDocument.openData(controller.pdfContracheque!),
                    );
                    return Container(
                        width: MediaQuery.of(context).size.width * 0.9,
                        height: 300,
                        child: PdfView(
                          controller: pdfController,
                        ));
                  })
```

![image](https://user-images.githubusercontent.com/12227024/149241101-4bca9abc-b88c-456b-8a61-d9bd269a6276.png)

```yaml
name: riodasostrasapp
description: App Oficial da Prefeitura de Rio das Ostras
version: 1.2.6+6
publish_to: none
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #para o Quiz
  font_awesome_flutter: ^9.2.0 #Null safety full
  flutter_custom_clippers: ^2.0.0 #Null safety full
  html_unescape: ^2.0.0 #Null safety full
  auto_size_text: ^3.0.0 #Null safety full
  connectivity_plus: ^2.1.0 #Null safety full
  url_launcher: ^6.0.17 #Null safety full
  share_plus: ^3.0.4 #Null safety share_plus
  map_launcher: ^2.1.1 #Null safety 
  platform_device_id: ^1.0.1 #Null safety full
  #location_permissions: ^4.0.1  # foi substituído pelo permission_handler 8.3.0  #Null safety
  location: ^4.3.0 #Null safety
  flutter_inappwebview: ^5.3.2 #Null safety  
  firebase_messaging: ^11.2.4 #Null safety  
  shared_preferences: ^2.0.11 #Null safety full
  sqflite: ^2.0.1 #Null safety 
  path_provider: ^2.0.8 #Null safety
  flutter_advanced_networkimage_2: ^2.0.0 #Null safety full
  cached_network_image: ^3.2.0 #Null safety 
  webview_flutter: ^3.0.0 #Null safety 
  flutter_map: ^0.14.0 #Null safety full
  latlong2: ^0.8.1 #Null safety full
 # queries: ^0.1.15 
  collection: ^1.15.0 #Null safety
  intl: ^0.17.0 #Null safety full
  http: ^0.13.4 #Null safety full
  dio: ^4.0.4 #Null safety full  
  universal_html: ^2.0.8 #Null safety full
   
  #wideget para infinit scroll
  incrementally_loading_listview: ^1.0.0 #Null safety
  mobx: any
  flutter_mobx: any 
  provider: ^6.0.1 #Null safety full  
  flutter_modular: ^4.3.0  #Null safety full
  equatable: ^2.0.3 #Null safety full
  carousel_slider: ^4.0.0 #Null safety full
  #para armazenar o token  
  flutter_secure_storage: ^5.0.2 #Null safety full 
  jaguar_jwt: ^3.0.0 #Null safety
  barcode_scan2: ^4.2.0  #Null safety full
  #gerar codigo qr
  #qr_flutter: ^4.0.0  # Null safety full     
  pdf: ^3.6.5 #Null safety full
  #printing: ^5.3.0 #Null safety full
  native_pdf_view: ^5.0.0
  qr: ^3.0.0 #Null safety full

  riodasostrasapp_core:
    path: ../riodasostrasapp_core
   # hosted:
   #   name: riodasostrasapp_core
   #   url: http://pub.riodasostras.rj.gov.br:4000
   # version: ^1.0.39

dependency_overrides:
  rxdart: ^0.27.3 #Null safety full
  

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  mockito: ^4.1.1
  build_runner: ^2.1.7 #Null safety
  mobx_codegen: ^2.0.4 #Null safety
  slidy: ^3.2.2+2 #Null safety full

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700      
    - family: pmro_app
      fonts:
        - asset: assets/fonts/pmro.ttf         
     
   
scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
      
```
