### ISSUE TITLE
Increase dependency on device_info_plus to 11.2.1

### ISSUE THREAD

**Issue by ghost** [rbcprolabs/packages.flutter#551]
This package's dependency on [device_info_plus](https://pub.dev/packages/device_info_plus) 10.1.2 is preventing me from updating my dependency on device_info_plus

Please update to the latest version

**Comment by hanandewa5** [comment]
you can use this as temporary solution before officially updated
```
dependencies:
  ...
  pdfx: 2.8.0
  device_info_plus: ^11.3.3

dependency_overrides:
  device_info_plus: ^11.3.3
```
